export const BUILTIN_THEME_ID = "builtin";
export const SCHEMA_VERSION = 1;

/**
 * @param {Record<string, string>} target
 * @param {string} stem
 * @param {string} icon
 * @param {string[]} [suffixes]
 */
function assignConfigVariants(
	target: Record<string, string>,
	stem: string,
	icon: string,
	suffixes = ["json", "json5", "yml", "yaml", "toml", "js", "cjs", "mjs"],
) {
	target[stem] = icon;
	for (const suffix of suffixes) {
		target[`${stem}.${suffix}`] = icon;
	}
}

function createFileNames() {
	const fileNames: Record<string, string> = {
		"yarn.lock": "yarn",
		".yarnrc": "yarn",
		".yarnrc.yml": "yarn",
		"package.json": "npm",
		"package-lock.json": "npm",
		"npm-shrinkwrap.json": "npm",
		".npmrc": "npm",
		".nvmrc": "npm",
		"jsconfig.json": "jsconfig",
		"tsconfig.json": "tsconfig",
		"tsconfig.build.json": "tsconfig",
		"tsconfig.app.json": "tsconfig",
		"tsconfig.node.json": "tsconfig",
		"jsconfig.build.json": "jsconfig",
		".jsbeautifyrc": "jsbeautify",
		"webpack.config.js": "webpack",
		"webpack.config.cjs": "webpack",
		"webpack.config.mjs": "webpack",
		"webpack.config.ts": "webpack",
		"webpack.config.babel.js": "webpack",
		"rollup.config.js": "rollup",
		"rollup.config.mjs": "rollup",
		"rollup.config.ts": "rollup",
		"tailwind.config.js": "tailwind",
		"tailwind.config.cjs": "tailwind",
		"tailwind.config.mjs": "tailwind",
		"tailwind.config.ts": "tailwind",
		".gitignore": "git",
		".gitattributes": "git",
		".gitmodules": "git",
		".gitkeep": "git",
		".mailmap": "git",
		".dockerignore": "docker",
		dockerfile: "docker",
		Dockerfile: "docker",
		"Dockerfile.dev": "docker",
		"Dockerfile.prod": "docker",
		"docker-compose.yml": "docker",
		"docker-compose.yaml": "docker",
		"compose.yml": "docker",
		"compose.yaml": "docker",
		makefile: "makefile",
		Makefile: "makefile",
		GNUmakefile: "makefile",
		"CMakeLists.txt": "cmake",
		LICENSE: "license",
		LICENCE: "license",
		COPYING: "license",
		"LICENSE.md": "license",
		"LICENSE.txt": "license",
		Gemfile: "ruby",
		Rakefile: "ruby",
		Guardfile: "ruby",
		"Cargo.toml": "rust",
		"Cargo.lock": "rust",
		"go.mod": "golang",
		"go.sum": "golang",
		"composer.json": "php",
		"composer.lock": "php",
		".htaccess": "apache",
		".htpasswd": "htpasswd",
		".editorconfig": "ini",
		".babelrc": "babel",
		"babel.config.js": "babel",
		"babel.config.cjs": "babel",
		"babel.config.json": "babel",
		".prettierrc": "prettier",
		"prettier.config.js": "prettier",
		"prettier.config.cjs": "prettier",
		"prettier.config.mjs": "prettier",
		".eslintrc": "eslint",
		"eslint.config.js": "eslint",
		"eslint.config.cjs": "eslint",
		"eslint.config.mjs": "eslint",
		"eslint.config.ts": "eslint",
		"eslint.config.json": "eslint",
		".postcssrc": "postcssconfig",
		"postcss.config.js": "postcssconfig",
		"postcss.config.cjs": "postcssconfig",
		"postcss.config.mjs": "postcssconfig",
		"postcss.config.json": "postcssconfig",
		"androidmanifest.xml": "android",
		"AndroidManifest.xml": "android",
		"build.gradle": "gradle",
		"build.gradle.kts": "gradle",
		"settings.gradle": "gradle",
		"settings.gradle.kts": "gradle",
		"gradle.properties": "gradle",
		"pom.xml": "java",
		"mix.exs": "elixir",
		"pubspec.yaml": "dartlang",
		"pubspec.yml": "dartlang",
		"pyproject.toml": "python",
		"requirements.txt": "python",
		Pipfile: "python",
		"Pipfile.lock": "python",
		"poetry.lock": "python",
		Procfile: "text",
		Jenkinsfile: "groovy",
		Vagrantfile: "ruby",
		"gulpfile.js": "javascript",
		"Gruntfile.js": "javascript",
		"vite.config.js": "javascript",
		"vite.config.ts": "javascript",
		"svelte.config.js": "svelte",
		"astro.config.mjs": "astro",
		"next.config.js": "javascript",
		"nuxt.config.js": "javascript",
		"vercel.json": "json",
		"netlify.toml": "toml",
		"wrangler.toml": "toml",
		"firebase.json": "json",
		".firebaserc": "json",
		"robots.txt": "text",
		"sitemap.xml": "xml",
		".env": "ini",
		".env.local": "ini",
		".env.development": "ini",
		".env.production": "ini",
		".env.test": "ini",
	};

	assignConfigVariants(fileNames, ".eslintrc", "eslint");
	assignConfigVariants(fileNames, ".prettierrc", "prettier");
	assignConfigVariants(fileNames, ".postcssrc", "postcssconfig");
	assignConfigVariants(fileNames, ".babelrc", "babel", [
		"json",
		"js",
		"cjs",
		"mjs",
	]);

	return fileNames;
}

function createFileExtensions() {
	const fileExtensions: Record<string, string> = {
		"js.map": "jsmap",
		"css.map": "cssmap",
		"test.js": "testjs",
		"spec.js": "testjs",
		"test.jsx": "testjs",
		"spec.jsx": "testjs",
		"test.ts": "testts",
		"spec.ts": "testts",
		"test.tsx": "testts",
		"spec.tsx": "testts",
		"d.ts": "typescriptdef",
		cljs: "clojurescript",
		hh: "cppheader",
		hpp: "cppheader",
		hxx: "cppheader",
		apk: "android",
		aab: "android",
		slim: "android",
		mp3: "audio",
		wav: "audio",
		ogg: "audio",
		flac: "audio",
		aac: "audio",
		mp4: "video",
		m4a: "video",
		mov: "video",
		"3gp": "video",
		wmv: "video",
		flv: "video",
		avi: "video",
		webm: "video",
		mkv: "video",
		png: "image",
		jpg: "image",
		jpeg: "image",
		gif: "image",
		bmp: "image",
		ico: "image",
		webp: "image",
		avif: "image",
		svg: "svg",
		zip: "compressed",
		rar: "compressed",
		"7z": "compressed",
		tar: "compressed",
		gz: "compressed",
		gzip: "compressed",
		tgz: "compressed",
		"tar.gz": "compressed",
		dmg: "compressed",
		iso: "compressed",
		bz2: "compressed",
		xz: "compressed",
	};

	return fileExtensions;
}

export function createBuiltinTheme() {
	return {
		id: BUILTIN_THEME_ID,
		name: "Builtin",
		schemaVersion: SCHEMA_VERSION,
		fileNames: createFileNames(),
		fileExtensions: createFileExtensions(),
		file: "file",
		folder: "folder",
		folderExpanded: "folder",
		rootFolder: "folder",
		rootFolderExpanded: "folder",
	};
}
