name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  merge_group:

jobs:
  spell-check:
    timeout-minutes: 5
    name: Check spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check spelling
        uses: crate-ci/typos@master
        with:
          config: ./_typos.toml

  quality:
    timeout-minutes: 5
    name: Linting and formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1

      - name: Run Biome
        run: biome ci .

  unit-tests:
    name: Unit Tests (On PR Only)
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Run unit tests
        run: npm run test

  translation-check:
    name: Translation Check (On PR Only)
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: read
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Detect Changed Files
        uses: dorny/paths-filter@v4
        id: file-changes
        with:
          list-files: shell
          filters: |
            translation:
              - 'src/lang/*.json'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Translation Files Check (if changed)
        if: steps.file-changes.outputs.translation == 'true'
        run: |
            npm ci --no-audit --no-fund
            npm run lang check
